# Generated by Django 4.0.4 on 2022-05-12 02:43

from django.db import migrations


def populate_section(apps, schemaeditor):
    section_types = {
        "reader": "A subcriber to the newspaper",
        "journalist": "A staff member that creates content",
        "editor": "A staff member that is in charge of editing",
    }
    UserType = apps.get_model('accounts', 'UserType')
    for name, desc in user_types.items():
        user_type = UserType(name=name, description=desc)
        user_type.save()





class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
